version:  1.0.1
server:
    port: 3000
db: test
swagger:
    info:
        title: AppDock Server
        version: 1.0.1
        description: AppDock server API description
    host: localhost:3000
    basePath: /